# Generated by Django 2.2.5 on 2021-02-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_detail',
            old_name='postion',
            new_name='position',
        ),
    ]
